# Generated by Django 5.2.6 on 2025-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_video', models.FileField(upload_to='videos/')),
                ('extracted_audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('status', models.CharField(default='pending', max_length=32)),
                ('status_message', models.TextField(blank=True, default='')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('image_findings_json', models.JSONField(blank=True, null=True)),
                ('summarized_report', models.TextField(blank=True, default='')),
            ],
        ),
    ]
