# Generated by Django 5.2.6 on 2025-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='incident_date',
            field=models.DateField(blank=True, help_text='Date of the incident', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('traffic-stop', 'Traffic Stop'), ('domestic', 'Domestic Dispute'), ('theft', 'Theft/Burglary'), ('assault', 'Assault'), ('drug', 'Drug Related'), ('other', 'Other')], help_text='Type of incident', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional incident notes'),
        ),
        migrations.AddField(
            model_name='report',
            name='officer_badge',
            field=models.CharField(blank=True, help_text='Officer badge number', max_length=20),
        ),
    ]
