# Generated by Django 5.2.6 on 2025-09-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_report_incident_date_report_incident_type_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE main_report RENAME COLUMN officer_id TO officer_badge;",
            reverse_sql="ALTER TABLE main_report RENAME COLUMN officer_badge TO officer_id;"
        ),
    ]
