# Generated by Django 5.2.6 on 2025-09-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250913_1307'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE main_report DROP COLUMN progress_percent;",
            reverse_sql="ALTER TABLE main_report ADD COLUMN progress_percent INTEGER DEFAULT 0;"
        ),
    ]
