# Generated by Django 5.2.6 on 2025-09-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250913_1643'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE main_report_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at datetime NOT NULL,
                updated_at datetime NOT NULL,
                original_video varchar(100) NOT NULL,
                extracted_audio varchar(100),
                status varchar(20) NOT NULL DEFAULT 'pending',
                status_message TEXT NOT NULL DEFAULT '',
                image_findings_json TEXT,
                summarized_report TEXT NOT NULL DEFAULT '',
                incident_date date,
                incident_type varchar(50),
                notes TEXT NOT NULL DEFAULT '',
                transcript_text TEXT NOT NULL DEFAULT '',
                officer_badge varchar(20) DEFAULT ''
            );
            INSERT INTO main_report_new SELECT 
                id, created_at, updated_at, original_video, extracted_audio, 
                status, status_message, image_findings_json, summarized_report,
                incident_date, incident_type, notes, transcript_text, 
                CAST(officer_badge AS TEXT) as officer_badge
            FROM main_report;
            DROP TABLE main_report;
            ALTER TABLE main_report_new RENAME TO main_report;
            """,
            reverse_sql="-- Cannot reverse table recreation"
        ),
    ]
