# Generated by Django 5.2.6 on 2025-09-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250913_1644'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the document content', max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='signature_tx_hash',
            field=models.CharField(blank=True, help_text='XRPL transaction hash of the signature', max_length=64),
        ),
        migrations.AddField(
            model_name='report',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='When the document was digitally signed', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='signed_by',
            field=models.ForeignKey(blank=True, help_text='Officer who digitally signed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OfficerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=50, unique=True)),
                ('encrypted_secret', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
