# Generated by Django 5.2.6 on 2025-09-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_report_document_hash_report_signature_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerwallet',
            name='credential_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When credential was accepted', null=True),
        ),
        migrations.AddField(
            model_name='officerwallet',
            name='credential_created_at',
            field=models.DateTimeField(blank=True, help_text='When credential was created', null=True),
        ),
        migrations.AddField(
            model_name='officerwallet',
            name='credential_data',
            field=models.JSONField(blank=True, help_text='Credential data from XRPL', null=True),
        ),
        migrations.AddField(
            model_name='officerwallet',
            name='credential_id',
            field=models.CharField(blank=True, help_text='XLS-70 Credential ID', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='credential_id',
            field=models.CharField(blank=True, help_text='XLS-70 Credential ID used for signing', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='signature_type',
            field=models.CharField(choices=[('MOCK', 'Mock Signature (Testing)'), ('XLS70_CREDENTIAL', 'XLS-70 Credential Signature'), ('LEGACY', 'Legacy Transaction Memo')], default='MOCK', help_text='Type of digital signature used', max_length=20),
        ),
    ]
